[package]
name = "raytracer"
version = "0.1.0"
authors = ["Calvin Figuereo-Supraner <mail@calvin.page>"]
edition = "2018"

[workspace]

[dependencies]
clap = "3.0.0-beta.2"
image = "0.23.12"
rtlib = { path = "rtlib" }
